import {
  attribute,
  autoGeneratedHashKey,
  rangeKey,
  table,
  versionAttribute,
} from '@aws/dynamodb-data-mapper-annotations';

@table('portfolios')
class Portfolio {
  @autoGeneratedHashKey()
  id!: string;

  @attribute({memberType: 'String'})
  firstName!: string;

  @attribute({memberType: 'String'})
  lastName!: string;

  @attribute({memberType: 'String'})
  profileImage?: string;

  @attribute({memberType: 'String'})
  description?: string;

  @attribute({memberType: 'String'})
  twitterProfile?: string;

  @rangeKey({
    type: 'Date',
    defaultProvider: () => new Date(),
  })
  createdAt!: Date;

  @rangeKey({
    type: 'Date',
    defaultProvider: () => new Date(),
  })
  updatedAt!: Date;

  @versionAttribute()
  _v!: number;
}
export default Portfolio;
